version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug-env
    restart: always
    environment:
      - DEV_DATABASE_URL=postgresql://postgres:password@db:5432/talk_tidbits
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/code
    networks:
    - backend
    depends_on:
      - db

  db:
  # docker-compose exec web flask db init
  # docker-compose exec web flask db migrate
  # docker-compose exec web flask db upgrade
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talk_tidbits
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  db-data: {}
