"""empty message

Revision ID: 27157fb66cf5
Revises: 8393d2f5e166
Create Date: 2023-03-28 04:27:35.263604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '27157fb66cf5'
down_revision = '8393d2f5e166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transcription_source_enum = postgresql.ENUM('local', 'openai', name='transcription_source_enum')
    transcription_source_enum.create(op.get_bind())
    
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription_source', sa.Enum('local', 'openai', name='transcription_source_enum'), nullable=True))
    
    default_transcription_source = "local"
    op.execute(f"UPDATE transcriptions SET transcription_source = '{default_transcription_source}' WHERE transcription_source IS NULL")
    
    op.alter_column('transcriptions', 'transcription_source', nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_column('transcription_source')

    # ### end Alembic commands ###
