"""empty message

Revision ID: 40891b7c10ae
Revises: a1bd988bdc13
Create Date: 2023-03-27 03:51:58.651597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40891b7c10ae'
down_revision = 'a1bd988bdc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=32), nullable=False))
        batch_op.drop_constraint('transcriptions_unique_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('transcriptions_unique_id_key', ['unique_id'])
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
