"""empty message

Revision ID: 70142e7867a1
Revises: b05a273bb81b
Create Date: 2023-03-28 04:12:04.049741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70142e7867a1'
down_revision = 'b05a273bb81b'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transcriptions', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('transcription_source', sa.Enum('local', 'openai', name='transcription_source_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('transcriptions', schema=None) as batch_op:
    #     batch_op.drop_column('transcription_source')

    # ### end Alembic commands ###
