"""empty message

Revision ID: ce9454e5b264
Revises: 7a32de298a26
Create Date: 2023-03-28 03:19:55.319612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9454e5b264'
down_revision = '7a32de298a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.drop_constraint('transcriptions_file_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint('transcriptions_file_name_key', ['file_name'])

    # ### end Alembic commands ###
