"""empty message

Revision ID: 7a32de298a26
Revises: 40891b7c10ae
Create Date: 2023-03-27 04:43:10.938522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a32de298a26'
down_revision = '40891b7c10ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.Text(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('transcription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcription_id'], ['transcriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    # ### end Alembic commands ###
